---
title: "analyse initiale"
author: "jcb"
date: "24 juin 2015"
output: html_document
---
```{r init, echo=FALSE}
library(knitr)
```

Apprenants
==========
```{r names, echo=FALSE}
file <- "../data/apprenants_2015-06-22.csv"
ap <- read.csv(file)
names(ap)

# pb pour différencier les groupes avec et sans prébriefing. Que signifie FDP et FMN . Pourquoi certaines lignes sont identiques (2 fois O ou N) ?
# dans le tableau des stat, sur la page formateur il y a une colonne pré birefing. tous les étudiants des groupes 2, 3, 7 et 8 ont eu un pre-briefing spécifique sur la mort possible du mannequin. les groupes 1,4,5 et 6 n'ont eu que le briefing classique.
#FDP c'est s'ils avaient dejà eu des cours auparavant sur la gestion de la mort
#FMN c'est s'ils avaient dejà eu des cours auparavant sur l'annonce de mauvaises nouvelles

# faire un score avec les 8 premier items
```


Groupes
-------
- nombre de groupes: `r length(unique(ap$Groupe_ID))`
- nombre d'apprenants par groupes:
```{r groupe, echo=FALSE, comment=""}
g <- tapply(ap$ID_Etud, ap$Groupe_ID, length)
g
g.m <- mean(g)
g.r <- range(g)
```
- nombre moyen d'apprenants par groupe: `r g.m`
- étendue: `r g.r[1]` - `r g.r[2]`

Rôle
----
```{r role, echo=FALSE,comment=""}
summary(as.factor(ap$ROLE))

```

Répartition des apprenants par groupes
---------------------------------------
```{r app_gr, echo=FALSE,comment=""}
table(ap$ROLE, ap$Groupe_ID,dnn = c("APPRENANTS","GROUPE"))
```

Sexe
----
```{r sex, echo=FALSE, comment=""}
summary(as.factor(ap$SEXE))

```

Profession
----------
```{r prof, echo=FALSE, comment=""}
summary(ap$PROF)

```

Etudes
------
```{r etudes, echo=FALSE, comment=""}
summary(ap$ETUDE)
summary(as.factor(ap$ETUDE))

```
FDP
---
```{r fdp, echo=FALSE, comment=""}
summary(ap$FDP)

```

FMN
---
```{r fmn, echo=FALSE,comment=""}
summary(ap$FMN)

```
Création d'une colonne pré-briefing
====================================
```{r preb, echo=FALSE, comment=""}
# création d'une colonne PREB selon que l'apprenant ait eu ou non un prébriefing
ap$PREB <- NA
ap$PREB[ap$Groupe_ID %in% c(2, 3, 7, 8)] <- "O"
ap$PREB[ap$Groupe_ID %in% c(1,4,5, 6)] <- "N"
table(ap$PREB, dnn = "Pré-briefing")

```

Sexe et préb
------------
```{r}
table(ap$SEXE, ap$PREB)
```

