---
title: "Mémoire d'Anne Weiss: score deLikert"
author: "jcb"
date: "24 juin 2015"
output:
  pdf_document:
    number_sections: yes
    toc: yes
---

```{r init, echo=FALSE}
library(likert)
options(digits = 3)

file <- "../../data/likert_avant_2015-06-22.csv"
lk.av <- read.csv(file)
file <- "../../data/likert_apres_2015-06-22.csv"
lk.ap <- read.csv(file)
# suppression des colonnes éxcédentaires
lk.ap <- lk.ap[, 1:15]
# renommer les colonnnes avant et après
a <- names(lk.av)
a <- c(a[1:3], paste(a[4:15],".av", sep = ""))
names(lk.av) <- a

a <- names(lk.ap)
a <- c(a[1:3], paste(a[4:15],".ap", sep = ""))
names(lk.ap) <- a
# tableau global
lkt <- cbind(lk.av, lk.ap[, 4:12])
# ajout colonne PREB
lkt$PREB[lkt$Groupe_ID %in% c(2, 3, 7, 8)] <- "O"
lkt$PREB[lkt$Groupe_ID %in% c(1,4,5, 6)] <- "N"
```

Les items de Likert correspondent aux colonnes 4 à 15

Scores de Likert avant
-----------------------
```{r score_avant, warning=FALSE, echo=FALSE}
# score de Likert avant et après
lik.av <- lk.av[, c(4:15)]

likert(lik.av, nlevels = 8)
plot(likert(lik.av, nlevels = 8))
summary(lik.av, nlevels = 8)

```

Score de Likert après
---------------------
```{r score_apres, warning=FALSE, echo=FALSE}
lik.ap <- lk.ap[, c(4:15)]

likert(lik.ap, nlevels = 8)
plot(likert(lik.ap, nlevels = 8))
summary(lik.ap, nlevels = 8)

```


Note: pour étudier une colonne seule, il faut utiliser la syntaxe suivante:
```{r, warning=FALSE}
q1a <- lk.av[, 4, drop = FALSE]
# plot likert
plot(likert(q1a,nlevels = 8))
# summary spécifique
summary(likert(q1a,nlevels = 8))
# %
likert(q1a, nlevels = 8)
# nombre
table(q1a)

```

Q1 avant et après
```{r Q1, warning=FALSE}
q1a <- lk.av[, 4, drop = FALSE]
q1p <- lk.ap[, 4, drop = FALSE]
q1 <- cbind(q1p, q1a)
names(q1) <- c("Q1.Ap","Q1.Av")
plot(likert(q1, nlevels = 8))
likert.bar.plot(likert(q1, nlevels = 8), main = "Q1")
likert.heat.plot(likert(q1, nlevels = 8), main = "Q1")
likert.density.plot(likert(q1, nlevels = 8), main = "Q1", warning = FALSE)

summary(likert(q1, nlevels = 8))

# test du chi2 pour comparer avant-après
c <- likert(q1, nlevels = 8)
# c est un objet de type likert dont il faut extraire les données (voir str(c))
d <- c$results[,2:9]
# on regroupe les colonnes 6 et 7 pour avoir des effectifs convenables
d[,6] <-d[,6]+d[,7]
# test en éliminant le colonne 8 qui est nulle
chisq.test(d[, 1:6])


```

